services:
  - type: web
    name: shoplist-pro
    env: php
    region: oregon
    buildCommand: |
      composer install --optimize-autoloader --no-dev
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: |
      php artisan migrate --force
      php -S 0.0.0.0:$PORT -t public
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: ShopList Pro
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://shoplist-pro.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file